version: "3.5"

services:
  server:
    restart: always

    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file: ./server/.env
    depends_on:
      - mongodb
    networks:
      - share
    ports:
      - 8080:8080
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - share-mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    networks:
      - share
  client:
    restart: always
    build:
      context: ./client
      dockerfile: ./Dockerfile
    env_file: ./client/.env
    depends_on:
      - server
    networks:
      - share
    ports:
      - 3000:3000

networks:
  share:
    name: share

volumes:
  share-mongodb-data:
