module.exports = {
  images: [
    'image/png',
    'image/jpeg',
    'image/gif',
    'image/bmp',
    'image/vnd.microsoft.icon',
    'image/webp'
  ],
  video: [
    'video/x-msvideo',
    'video/mpeg',
    'video/mp2t',
    'video/3gpp',
    'video/3gpp2',
    'video/x-flv',
    'video/mp4'
  ],
  files: [
    'application/zip',
    'application/x-zip',
    'application/x-zip-compressed',
    'application/octet-stream',
    'application/x-compress',
    'application/x-compressed',
    'multipart/x-zip',
    'application/x-tar',
    'application/x-rar-compressed',
    'audio/mpeg',
    'video/mpeg',
    'image/png',
    'image/photoshop',
    'image/x-photoshop',
    'image/psd',
    'application/photoshop',
    'application/psd',
    'zz-application/zz-winassoc-psd',
    'application/msword',
    'application/doc',
    'appl/text',
    'application/vnd.msword',
    'application/vnd.ms-word',
    'application/winword ',
    'application/word',
    'application/x-msw6',
    'application/x-msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-excel',
    'application/msexcel',
    'application/x-msexcel',
    'application/x-ms-excel',
    'application/vnd.ms-excel',
    'application/x-excel',
    'application/x-dos_ms_excel',
    'application/xls'
  ],
  text: ['text/plain']
};
